### ISSUE TITLE
The extension stops working automatically.

### ISSUE THREAD

**Issue by ash1247** [georgewfraser/java-language-server#108] opened 2019-08-21 14:56 UTC
Issue Type: <b>Bug</b>

The extension stops working when I try to use intellisense or open a new java file. Says Extension host terminated unexpectedly.

Extension version: 0.2.21
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:25.463Z)
OS version: Linux x64 5.0.0-23-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3437U CPU @ 1.90GHz (4 x 2693)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|11.60GB (3.38GB free)|
|Process Argv|--unity-launch /home/ash1247/pers/Documents/Java/Networking|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by georgewfraser** [comment] 2019-08-24 17:37
Is this still happening with the latest version?

**Comment by georgewfraser** [comment] 2019-08-24 17:52
Duplicate of #106

**Closed by georgewfraser** 2019-08-24 17:52 UTC
